/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-14 05:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.rrr;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<Style>\n");
      out.write("header h1{\n");
      out.write("text-align:left;\n");
      out.write("heidht:25%;\n");
      out.write("width:100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("html,body{\n");
      out.write("width:100%;\n");
      out.write("height:100%;\n");
      out.write("}\n");
      out.write("*{\n");
      out.write("padding:0%;\n");
      out.write("margin:0%;\n");
      out.write("}\n");
      out.write("#app{\n");
      out.write("width:100px;\n");
      out.write("}\n");
      out.write("hh{\n");
      out.write("flat: left;\n");
      out.write("font-size: 70px;\n");
      out.write("}\n");
      out.write("jj{\n");
      out.write("float: right;\n");
      out.write("font-size:20px;\n");
      out.write("vertical-align: middle;\n");
      out.write("}\n");
      out.write("</Style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header>\n");

	String checkName="";
	checkName=(String)session.getAttribute("s_Name");
	if(checkName==null){

      out.write("\n");
      out.write("<hh>\n");
      out.write("카 센터(붕붕이 나라)\n");
      out.write("</hh>\n");
      out.write("<jj>\n");
      out.write("<form method=\"post\" action=\"login.jsp\">\n");
      out.write("<fieldset>\n");
      out.write("<label for=\"ID\">회원ID:</label>\n");
      out.write("<input id=\"app\" type=\"text\" name=\"id\" size=\"10\" maxlength=\"10\" required=\"required\"/>\n");
      out.write("<label for=\"pswd\">비밀번호:</label>\n");
      out.write("<input id=\"app\" type=\"text\" name=\"passwd\" size=\"10\" maxlength=\"10\" required=\"required\"/>|\n");
      out.write("<input type=\"submit\" value=\"로그인\" data-inline=\"true\">\n");
      out.write("<input type=\"button\" value=\"회원가입\" onclick=\"location.href='member.jsp'\">\n");
      out.write("</fieldset>\n");
      out.write("</form>\n");
      out.write("</jj>\n");
      out.write("</header>\n");
}else{session.setMaxInactiveInterval(500);
      out.write("\n");
      out.write("<hh><label onclick=\"location.href='main.jsp'\">카센터(붕붕이 나라)</label></hh>\n");
      out.print(checkName );
      out.write("님 환영합니다.\n");
      out.write("\t<a href=\"logout.jsp\">logout</a>\n");
      out.write("\t<a href=\"member.jsp\">회원가입</a>\n");
      out.write("\t");
} 
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
