/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.44
 * Generated at: 2021-04-20 02:12:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.hrd0415;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class reservationInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/hrd0415/DBconnOracle.jsp", Long.valueOf(1618819633403L));
    _jspx_dependants.put("/hrd0415/header.jsp", Long.valueOf(1618448820152L));
    _jspx_dependants.put("/hrd0415/nav.jsp", Long.valueOf(1618792806340L));
    _jspx_dependants.put("/hrd0415/footer.jsp", Long.valueOf(1618449233832L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>도서 회원 관리</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function check1(str){\r\n");
      out.write("\tif(document.form.lentno.value==\"\"){\r\n");
      out.write("\t\talert(\"대출번호가 입력되지 않음\");\r\n");
      out.write("\t\tdocument.form.lentno.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.form.custname.value==\"\"){\r\n");
      out.write("\t\talert(\"고객이름이 입력되지 않음\");\r\n");
      out.write("\t\tdocument.form.custname.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.form.bookno.value==\"\"){\r\n");
      out.write("\t\talert(\"도서번호가 입력되지 않음\");\r\n");
      out.write("\t\tdocument.form.bookno.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\tif(document.form.outdate.value==\"\"){\r\n");
      out.write("\t\talert(\"대출일자가 입력되지 않음\");\r\n");
      out.write("\t\tdocument.form.outdate.focus();\r\n");
      out.write("\t}else if(str==\"insert\"){\r\n");
      out.write("\t\tform.action=\"reservationProcess.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changesubmit(){\r\n");
      out.write("\tdocument.form.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"common.css\">\r\n");
      out.write("<header>\r\n");
      out.write("도서 회원 관리 ver1.0\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li><a href=\"bookinfoInsert.jsp\">도서정보등록</a></li>\r\n");
      out.write("\t\t<li><a href=\"reservationInsert.jsp\">도서 대출정보 등록</a></li>\r\n");
      out.write("\t\t<li><a href=\"bookinfoSelect.jsp\">도서 정보 조회</a></li>\r\n");
      out.write("\t\t<li><a href=\"reservationSelect.jsp\">도서 대출정보 조회</a></li>\r\n");
      out.write("\t\t<li><a href=\"index.jsp\">호무로</a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	request.setCharacterEncoding("utf-8");
	Connection conn=null;
	
	try{
	String url="jdbc:oracle:thin:@//localhost:1521/xe";
	String user="system";
	String pwd="1234";
	String jdbc_Driver="oracle.jdbc.OracleDriver";
	Class.forName(jdbc_Driver);
	
	conn = DriverManager.getConnection(url,user,pwd);
	System.out.println("db연결 완료");
	
	}catch (SQLException e){
		
		System.out.println("db연결 실패~!");
		System.out.println("SQLException: "+e.getMessage()); 
		e.printStackTrace();
	} 

      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');

	PreparedStatement pstmt=null;
	ResultSet rs=null;
	String bookno=request.getParameter("bookno");
	//System.out.println("북네임 에러1"+bookno);
	String lentno=request.getParameter("lentno");
	String custname=request.getParameter("custname");
	String outdate=request.getParameter("outdate"); //폼에서 가져오는 파라미터임
	String indate=request.getParameter("indate");
	
	
	//
	//System.out.println("error : "+bookno);
	//
	
	
	String bookname="";
	int sel=0;
	if(bookno==null){
		bookno="";
		bookname="";
		lentno="";
		custname="";
		outdate="";
		indate="";
	}else{
		
	
	String sql="select bookno,bookname from bookinfo0415 where bookno=?";
	pstmt=conn.prepareStatement(sql);
	pstmt.setString(1, bookno);
	rs=pstmt.executeQuery();
	if(rs.next()){
		bookname=rs.getString("bookname");
	}else{
		
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\talert(\"등록되지 않은 코드입니다.\");\r\n");
      out.write("\t\t\thistory.back(-1);\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");

	}
	}

      out.write("\r\n");
      out.write("<h3 id=\"r3\">도서 예약 정보 등록 화면</h3>\r\n");
      out.write("<form name=\"form\" method=post action=\"reservationInsert.jsp\">\r\n");
      out.write("<table border=1 id=\"tab1\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th width=\"20%\">대출번호</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"lentno\" value=\"");
      out.print(lentno);
      out.write("\"></td>\r\n");
      out.write("\t<th width=\"20%\">고객성명</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"custname\" value=\"");
      out.print(custname);
      out.write("\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th width=\"20%\">도서코드</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"bookno\" value=\"");
      out.print(bookno );
      out.write("\" onchange=\"javascript:changesubmit();\"></td>\r\n");
      out.write("\t<th width=\"20%\">도서이름</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"bookname\" value=\"");
      out.print(bookname );
      out.write("\"></td>\r\n");
      out.write("</tr><tr>\r\n");
      out.write("\t<th width=\"20%\">대출일자</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"outdate\" value=\"");
      out.print(outdate );
      out.write("\"></td>\r\n");
      out.write("\t<th width=\"20%\">반납일자</th>\r\n");
      out.write("\t<td><input id=\"in1\" type=\"text\" name=\"indate\" value=\"");
      out.print(indate );
      out.write("\" onchange=\"javascript:changesubmit();\"\r\n");
      out.write("\t\t");
 if(indate==""){sel=1;}else{sel=0;}
      out.write("></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th width=\"20%\">대출상태</th>\r\n");
      out.write("\t<td><input type=\"radio\" name=\"status\" value=\"1\" onchange=\"javascript:changesubmit();\"\r\n");
      out.write("\t\t");
 if(sel==1){
      out.write("checked");
} 
      out.write(">대출\r\n");
      out.write("\t\t<input type=\"radio\" name=\"status\" value=\"2\" onchange=\"javascript:changesubmit();\"\r\n");
      out.write("\t\t");
 if(sel==0){
      out.write("checked");
} 
      out.write(">반납</td>\r\n");
      out.write("\t<th width=\"20%\">등급</th>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<select id=\"in1\" name=\"class1\">\r\n");
      out.write("\t\t\t<option value=\"S\" selected>S</option>\r\n");
      out.write("\t\t\t<option value=\"a\" >a</option>\r\n");
      out.write("\t\t\t<option value=\"b\" >b</option>\r\n");
      out.write("\t\t\t<option value=\"c\" >c</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th colspan=4 align=center>\r\n");
      out.write("\t<button id=\"in2\" type=\"submit\" onclick='check1(\"insert\")'>저장</button>\r\n");
      out.write("\t<button id=\"in2\" type=\"reset\" >취소</button>\r\n");
      out.write("\t</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>HRDKOREA copyright</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
